language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
branches:
  only:
  - develop
install:
- npm install
- npm run generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: U/UuBZyMFVX9MMeJTSrJkS7qhukoGd6ppji9r8uX7Mjyr9s0YcMGuGdGuwy5dwREHpsTEXTpmY5OCL9SHumoBFC9P3MN30UKgs+hwiagGDD7tDY6aHuqwGw5eZ8/gv85hAGvdBEpAtZW/F1M266bZYFn4/Wlx8hRUj5W/4n8ixShrvuvz/x9HqDLbWQM5jN0zmn//N9wBZ6vi3yigSiY9dxqw58ZOYQyI96ZMs6pZH7W2y1QKHDbXEF7hmKO6hB2XgUT4gPvwqAnsdJMCHE54nUyHvaGZH2vHBHHcDyxOrHZg4x3eXJEFC/rupjjkRxzNRuatIrNhMa3fezrQ4eGyfYXbOx16RH2ThHdDr/wa9g6FY4d0tqtk5n7NDN2OX4i/l1pQdZ4F2ylpFMt7WaR8ZcepY3EGkRE746rGDOU2kLmo5vRqt9kd6R6zObRPl9keL5WspSG+M2c2Sx5lRiDZmo+mBiXTzyb9LQuDURQmBJqiezmg+f3X9NPVq2Xcao4J+GwH8nPUTIVRwHETixAm/nfOrNS5emgUbDs23HFC6tib8GWGtfhuxn1RXGFu6W2SXqSyrZd5zbzgcY/iWRq3xtp38rOo4PGfGqYpq2MXmw1cJejvTxXnek//WqIveIWaLid0irrqKh400FJYyVmX4J5tp0Xr32enyYR1kqkUEs=
  target-branch: master
  local-dir: dist
  on:
    branch: develop
